name: deploy-linux

on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [x64]
    steps:
      - uses: actions/checkout@v3

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 4: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          mkdir python
          pip install --platform manylinux2014_x86_64 --only-binary=:all: -r requirements_aws.txt -t python
          find python -type d -name "__pycache__" -exec rm -r {} +
          zip --quiet -r python.zip python

      # Step 7: Upload the executable as an artifact (optional, if needed)
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-python
          path: ./python.zip