name: deploy

on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'

      # Step 4: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Install PyInstaller and create the executable
      - name: Build Executable with PyInstaller
        run: |
          $userSite = "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages"
          echo "from PyInstaller.utils.hooks import collect_data_files" > $userSite\PyInstaller\hooks\hook-pyecharts.py
          echo "datas = collect_data_files('pyecharts')" >> $userSite\PyInstaller\hooks\hook-pyecharts.py
          pyinstaller -w --onefile --hidden-import pandas --hidden-import xlrd --hidden-import openpyxl --hidden-import pyecharts starter.py

      # Step 7: Upload the executable as an artifact (optional, if needed)
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-executable
          path: ./dist/starter.exe