name: deploy

on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'

      # Step 4: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Install PyInstaller and create the executable
      - name: Build Executable with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile starter.py

